#:schema node_modules/wrangler/config-schema.json
name = "firstdayfirstshow"
main = "src/index.js"
compatibility_date = "2024-06-20"


kv_namespaces = [
  { binding = "REVIEWS", id = "539e5146e21644c5a85bfce68a751e6c" }
]
[triggers]

crons = ["*/30 10-17 * * *"]  
